-- =============================================================================
-- 072_enterprise_payment_gateway.sql
-- Payment Engine: orders, intents, sessions, timeline, idempotency, webhooks
-- =============================================================================

CREATE TABLE IF NOT EXISTS payment_orders (
  id                BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid              CHAR(36)            NOT NULL,
  order_ref         VARCHAR(30)         NOT NULL,
  merchant_order_id VARCHAR(100)        NULL,
  merchant_id       BIGINT UNSIGNED     NOT NULL,
  organization_id   BIGINT UNSIGNED     NOT NULL,
  customer_id       BIGINT UNSIGNED     NULL,
  status            ENUM('draft','pending','paid','partial_paid','expired','cancelled','refunded') NOT NULL DEFAULT 'draft',
  currency          CHAR(3)             NOT NULL DEFAULT 'USD',
  amount            DECIMAL(18, 2)      NOT NULL,
  amount_paid       DECIMAL(18, 2)      NOT NULL DEFAULT 0.00,
  amount_refunded   DECIMAL(18, 2)      NOT NULL DEFAULT 0.00,
  description       TEXT                NULL,
  metadata          JSON                NULL,
  expires_at        DATETIME            NULL,
  created_by        BIGINT UNSIGNED     NULL,
  created_at        DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_orders_uuid (uuid),
  UNIQUE KEY uk_payment_orders_ref (order_ref),
  KEY idx_po_merchant_status (merchant_id, status),
  KEY idx_po_org_created (organization_id, created_at),
  KEY idx_po_merchant_order (merchant_id, merchant_order_id),
  KEY idx_po_customer (customer_id),
  CONSTRAINT fk_po_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_po_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_po_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_intents (
  id                    BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                  CHAR(36)            NOT NULL,
  intent_ref            VARCHAR(30)         NOT NULL,
  order_id              BIGINT UNSIGNED     NULL,
  merchant_id           BIGINT UNSIGNED     NOT NULL,
  organization_id       BIGINT UNSIGNED     NOT NULL,
  customer_id           BIGINT UNSIGNED     NULL,
  status                ENUM('pending','processing','authorized','captured','settled','failed','expired','refunded','partially_refunded','chargeback','cancelled') NOT NULL DEFAULT 'pending',
  amount                DECIMAL(18, 2)      NOT NULL,
  amount_captured       DECIMAL(18, 2)      NOT NULL DEFAULT 0.00,
  amount_refunded       DECIMAL(18, 2)      NOT NULL DEFAULT 0.00,
  currency              CHAR(3)             NOT NULL DEFAULT 'USD',
  payment_method_type_id TINYINT UNSIGNED   NULL,
  payment_method_code   VARCHAR(30)         NULL,
  idempotency_key       VARCHAR(64)         NULL,
  merchant_order_id     VARCHAR(100)        NULL,
  gateway_transaction_id VARCHAR(64)        NULL,
  acquirer_reference    VARCHAR(64)         NULL,
  rrn                   VARCHAR(64)         NULL,
  transaction_id        BIGINT UNSIGNED     NULL,
  metadata              JSON                NULL,
  failure_reason        VARCHAR(255)        NULL,
  expires_at            DATETIME            NULL,
  authorized_at         DATETIME            NULL,
  captured_at           DATETIME            NULL,
  settled_at            DATETIME            NULL,
  created_by            BIGINT UNSIGNED     NULL,
  created_at            DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_intents_uuid (uuid),
  UNIQUE KEY uk_payment_intents_ref (intent_ref),
  UNIQUE KEY uk_payment_intents_idempotency (merchant_id, idempotency_key),
  KEY idx_pi_merchant_status (merchant_id, status),
  KEY idx_pi_org_created (organization_id, created_at),
  KEY idx_pi_order (order_id),
  KEY idx_pi_transaction (transaction_id),
  KEY idx_pi_gateway_txn (gateway_transaction_id),
  KEY idx_pi_rrn (rrn),
  KEY idx_pi_status_created (status, created_at),
  CONSTRAINT fk_pi_order FOREIGN KEY (order_id) REFERENCES payment_orders (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pi_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_pi_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_pi_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pi_payment_method FOREIGN KEY (payment_method_type_id) REFERENCES payment_method_types (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_pi_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_sessions (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                CHAR(36)            NOT NULL,
  session_ref         VARCHAR(30)         NOT NULL,
  merchant_id         BIGINT UNSIGNED     NOT NULL,
  organization_id     BIGINT UNSIGNED     NOT NULL,
  customer_id         BIGINT UNSIGNED     NULL,
  order_id            BIGINT UNSIGNED     NULL,
  payment_intent_id   BIGINT UNSIGNED     NULL,
  status              ENUM('open','complete','expired','cancelled') NOT NULL DEFAULT 'open',
  amount              DECIMAL(18, 2)      NOT NULL,
  currency            CHAR(3)             NOT NULL DEFAULT 'USD',
  client_secret       VARCHAR(128)        NOT NULL,
  ip_address          VARCHAR(45)         NULL,
  user_agent          VARCHAR(512)        NULL,
  browser             VARCHAR(100)        NULL,
  device_id           BIGINT UNSIGNED     NULL,
  expires_at          DATETIME            NOT NULL,
  completed_at        DATETIME            NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_sessions_uuid (uuid),
  UNIQUE KEY uk_payment_sessions_ref (session_ref),
  KEY idx_ps_merchant_status (merchant_id, status),
  KEY idx_ps_intent (payment_intent_id),
  KEY idx_ps_expires (expires_at),
  CONSTRAINT fk_ps_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_ps_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_ps_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_ps_order FOREIGN KEY (order_id) REFERENCES payment_orders (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_ps_intent FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_ps_device FOREIGN KEY (device_id) REFERENCES payment_devices (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_timeline_events (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                CHAR(36)            NOT NULL,
  payment_intent_id   BIGINT UNSIGNED     NOT NULL,
  event_type          ENUM('created','intent','authorized','captured','settled','refunded','chargeback','failed','cancelled','expired','void') NOT NULL,
  from_status         VARCHAR(30)         NULL,
  to_status           VARCHAR(30)         NULL,
  description         VARCHAR(500)        NULL,
  metadata            JSON                NULL,
  actor_id            BIGINT UNSIGNED     NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pte_uuid (uuid),
  KEY idx_pte_intent (payment_intent_id, created_at),
  KEY idx_pte_type (event_type),
  CONSTRAINT fk_pte_intent FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pte_actor FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_idempotency_keys (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  key_hash            CHAR(64)            NOT NULL,
  merchant_id         BIGINT UNSIGNED     NOT NULL,
  organization_id     BIGINT UNSIGNED     NOT NULL,
  request_path        VARCHAR(200)        NOT NULL,
  response_status     SMALLINT UNSIGNED   NOT NULL,
  response_body       JSON                NOT NULL,
  expires_at          DATETIME            NOT NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pik_key_merchant (key_hash, merchant_id),
  KEY idx_pik_expires (expires_at),
  CONSTRAINT fk_pik_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pik_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_payment_methods (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                CHAR(36)            NOT NULL,
  customer_id         BIGINT UNSIGNED     NOT NULL,
  merchant_id         BIGINT UNSIGNED     NULL,
  organization_id     BIGINT UNSIGNED     NOT NULL,
  method_type         ENUM('card','upi','wallet','token','bnpl') NOT NULL,
  provider            VARCHAR(50)         NULL,
  last_four           CHAR(4)             NULL,
  brand               VARCHAR(30)         NULL,
  token_ref           VARCHAR(128)        NULL,
  vpa                 VARCHAR(100)        NULL,
  wallet_balance      DECIMAL(18, 2)      NOT NULL DEFAULT 0.00,
  is_default          TINYINT(1)          NOT NULL DEFAULT 0,
  is_active           TINYINT(1)          NOT NULL DEFAULT 1,
  metadata            JSON                NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cpm_uuid (uuid),
  KEY idx_cpm_customer (customer_id, is_active),
  KEY idx_cpm_merchant (merchant_id),
  CONSTRAINT fk_cpm_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_cpm_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cpm_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_webhook_deliveries (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                CHAR(36)            NOT NULL,
  merchant_id         BIGINT UNSIGNED     NOT NULL,
  payment_intent_id   BIGINT UNSIGNED     NULL,
  event_type          VARCHAR(50)         NOT NULL,
  webhook_url         VARCHAR(500)        NOT NULL,
  payload             JSON                NOT NULL,
  status              ENUM('pending','delivered','failed') NOT NULL DEFAULT 'pending',
  attempt_count       TINYINT UNSIGNED    NOT NULL DEFAULT 0,
  max_attempts        TINYINT UNSIGNED    NOT NULL DEFAULT 3,
  last_response_code  SMALLINT UNSIGNED   NULL,
  last_error          VARCHAR(500)        NULL,
  next_retry_at       DATETIME            NULL,
  delivered_at        DATETIME            NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pwd_uuid (uuid),
  KEY idx_pwd_merchant_status (merchant_id, status),
  KEY idx_pwd_intent (payment_intent_id),
  KEY idx_pwd_retry (status, next_retry_at),
  KEY idx_pwd_event (event_type, created_at),
  CONSTRAINT fk_pwd_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_pwd_intent FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE transactions
  ADD COLUMN payment_intent_id BIGINT UNSIGNED NULL AFTER customer_id,
  ADD KEY idx_transactions_payment_intent (payment_intent_id),
  ADD CONSTRAINT fk_transactions_payment_intent
    FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id)
    ON DELETE SET NULL ON UPDATE CASCADE;

-- Extended payment method types for gateway
INSERT INTO payment_method_types (code, name, icon_key, is_active) VALUES
('bnpl', 'Buy Now Pay Later', 'payments', 1),
('tap_to_pay', 'Tap To Pay', 'contactless', 1),
('softpos', 'SoftPOS', 'smartphone', 1),
('emi', 'EMI', 'credit_score', 1)
ON DUPLICATE KEY UPDATE name = VALUES(name);
