-- =============================================================================
-- 073_enterprise_hosted_checkout.sql
-- Hosted checkout sessions, branding, themes, events, analytics
-- Reuses payment_intents + payment_sessions (no duplicate payment tables)
-- =============================================================================

CREATE TABLE IF NOT EXISTS checkout_themes (
  id              INT UNSIGNED        NOT NULL AUTO_INCREMENT,
  uuid            CHAR(36)            NOT NULL,
  code            VARCHAR(50)         NOT NULL,
  name            VARCHAR(100)        NOT NULL,
  primary_color   VARCHAR(20)         NOT NULL DEFAULT '#003d9b',
  secondary_color VARCHAR(20)         NOT NULL DEFAULT '#64748b',
  accent_color    VARCHAR(20)         NOT NULL DEFAULT '#4f46e5',
  font_family     VARCHAR(80)         NOT NULL DEFAULT 'Inter, sans-serif',
  button_style    ENUM('rounded','pill','square') NOT NULL DEFAULT 'rounded',
  border_radius   VARCHAR(10)         NOT NULL DEFAULT '12px',
  dark_mode_ready TINYINT(1)          NOT NULL DEFAULT 1,
  is_active       TINYINT(1)          NOT NULL DEFAULT 1,
  created_at      DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_checkout_themes_uuid (uuid),
  UNIQUE KEY uk_checkout_themes_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS merchant_checkout_branding (
  id              BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid            CHAR(36)            NOT NULL,
  merchant_id     BIGINT UNSIGNED     NOT NULL,
  organization_id BIGINT UNSIGNED     NOT NULL,
  theme_id        INT UNSIGNED        NULL,
  logo_url        VARCHAR(500)        NULL,
  favicon_url     VARCHAR(500)        NULL,
  primary_color   VARCHAR(20)         NULL,
  secondary_color VARCHAR(20)         NULL,
  accent_color    VARCHAR(20)         NULL,
  font_family     VARCHAR(80)         NULL,
  button_style    ENUM('rounded','pill','square') NULL,
  border_radius   VARCHAR(10)         NULL,
  support_email   VARCHAR(255)        NULL,
  support_phone   VARCHAR(30)         NULL,
  terms_url       VARCHAR(500)        NULL,
  privacy_url     VARCHAR(500)        NULL,
  merchant_name   VARCHAR(255)        NULL,
  merchant_address TEXT               NULL,
  brand_banner_url VARCHAR(500)       NULL,
  allowed_origins JSON                NULL,
  dark_mode_default TINYINT(1)        NOT NULL DEFAULT 0,
  updated_by      BIGINT UNSIGNED     NULL,
  updated_at      DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_mcb_uuid (uuid),
  UNIQUE KEY uk_mcb_merchant (merchant_id),
  CONSTRAINT fk_mcb_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_mcb_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_mcb_theme FOREIGN KEY (theme_id) REFERENCES checkout_themes (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS checkout_sessions (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                CHAR(36)            NOT NULL,
  checkout_ref        VARCHAR(40)         NOT NULL,
  client_secret       VARCHAR(128)        NOT NULL,
  recovery_token      VARCHAR(64)         NOT NULL,
  payment_intent_id   BIGINT UNSIGNED     NOT NULL,
  payment_session_id  BIGINT UNSIGNED     NULL,
  order_id            BIGINT UNSIGNED     NULL,
  merchant_id         BIGINT UNSIGNED     NOT NULL,
  organization_id     BIGINT UNSIGNED     NOT NULL,
  customer_id         BIGINT UNSIGNED     NULL,
  amount              DECIMAL(18, 2)      NOT NULL,
  currency            CHAR(3)             NOT NULL DEFAULT 'USD',
  locale              VARCHAR(10)         NOT NULL DEFAULT 'en-US',
  theme_id            INT UNSIGNED        NULL,
  checkout_mode       ENUM('hosted','embed','popup') NOT NULL DEFAULT 'hosted',
  status              ENUM('open','complete','expired','cancelled','abandoned','pending') NOT NULL DEFAULT 'open',
  return_url          VARCHAR(500)        NULL,
  cancel_url          VARCHAR(500)        NULL,
  success_url         VARCHAR(500)        NULL,
  failure_url         VARCHAR(500)        NULL,
  pending_url         VARCHAR(500)        NULL,
  webhook_url         VARCHAR(500)        NULL,
  merchant_metadata   JSON                NULL,
  customer_email      VARCHAR(255)        NULL,
  customer_phone      VARCHAR(30)         NULL,
  billing_address     JSON                NULL,
  shipping_address    JSON                NULL,
  ip_address          VARCHAR(45)         NULL,
  user_agent          VARCHAR(512)        NULL,
  browser             VARCHAR(100)        NULL,
  device_type         VARCHAR(30)         NULL,
  os_name             VARCHAR(50)         NULL,
  country_code        CHAR(2)             NULL,
  retry_count         TINYINT UNSIGNED    NOT NULL DEFAULT 0,
  max_retries         TINYINT UNSIGNED    NOT NULL DEFAULT 3,
  last_failure_reason VARCHAR(255)        NULL,
  viewed_at           DATETIME            NULL,
  payment_started_at  DATETIME            NULL,
  completed_at        DATETIME            NULL,
  expires_at          DATETIME            NOT NULL,
  created_by          BIGINT UNSIGNED     NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_checkout_sessions_uuid (uuid),
  UNIQUE KEY uk_checkout_sessions_ref (checkout_ref),
  UNIQUE KEY uk_checkout_sessions_recovery (recovery_token),
  KEY idx_cs_merchant_status (merchant_id, status),
  KEY idx_cs_org_created (organization_id, created_at),
  KEY idx_cs_intent (payment_intent_id),
  KEY idx_cs_expires (expires_at),
  KEY idx_cs_status_created (status, created_at),
  CONSTRAINT fk_cs_intent FOREIGN KEY (payment_intent_id) REFERENCES payment_intents (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_cs_payment_session FOREIGN KEY (payment_session_id) REFERENCES payment_sessions (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_order FOREIGN KEY (order_id) REFERENCES payment_orders (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_cs_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_cs_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_cs_theme FOREIGN KEY (theme_id) REFERENCES checkout_themes (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS checkout_session_events (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  uuid                CHAR(36)            NOT NULL,
  checkout_session_id BIGINT UNSIGNED     NOT NULL,
  event_type          ENUM('created','viewed','payment_started','completed','failed','abandoned','expired','cancelled','retry','method_switched') NOT NULL,
  payment_method_code VARCHAR(30)         NULL,
  metadata            JSON                NULL,
  browser             VARCHAR(100)        NULL,
  os_name             VARCHAR(50)         NULL,
  country_code        CHAR(2)             NULL,
  device_type         VARCHAR(30)         NULL,
  created_at          DATETIME            NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cse_uuid (uuid),
  KEY idx_cse_session (checkout_session_id, created_at),
  KEY idx_cse_type (event_type, created_at),
  CONSTRAINT fk_cse_session FOREIGN KEY (checkout_session_id) REFERENCES checkout_sessions (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS checkout_analytics_daily (
  id                  BIGINT UNSIGNED     NOT NULL AUTO_INCREMENT,
  merchant_id         BIGINT UNSIGNED     NOT NULL,
  organization_id     BIGINT UNSIGNED     NOT NULL,
  analytics_date      DATE                NOT NULL,
  sessions_created    INT UNSIGNED        NOT NULL DEFAULT 0,
  sessions_viewed     INT UNSIGNED        NOT NULL DEFAULT 0,
  payments_started    INT UNSIGNED        NOT NULL DEFAULT 0,
  payments_completed  INT UNSIGNED        NOT NULL DEFAULT 0,
  payments_failed     INT UNSIGNED        NOT NULL DEFAULT 0,
  sessions_abandoned  INT UNSIGNED        NOT NULL DEFAULT 0,
  total_retries       INT UNSIGNED        NOT NULL DEFAULT 0,
  avg_completion_sec  INT UNSIGNED        NULL,
  conversion_rate     DECIMAL(5, 2)       NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_cad_merchant_date (merchant_id, analytics_date),
  KEY idx_cad_org_date (organization_id, analytics_date),
  CONSTRAINT fk_cad_merchant FOREIGN KEY (merchant_id) REFERENCES merchants (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_cad_org FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
