apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fintech-redis-data
  labels:
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
