flowchart TB
  N0["Component: Frontend_Fintech/src/app/app.c"]
  N1["Service: Frontend_Fintech/src/app/core/"]
  N2["Service: Frontend_Fintech/src/app/core/"]
  N3["Service: Frontend_Fintech/src/app/core/"]
  N4["Service: Frontend_Fintech/src/app/core/"]
  N5["Service: Frontend_Fintech/src/app/core/"]
  N6["Service: Frontend_Fintech/src/app/core/"]
  N7["Service: Frontend_Fintech/src/app/core/"]
  N8["Service: Frontend_Fintech/src/app/core/"]
  N9["Service: Frontend_Fintech/src/app/core/"]
  N10["Component: Frontend_Fintech/src/app/featu"]
  N11["Service: Frontend_Fintech/src/app/featu"]
  N12["Component: Frontend_Fintech/src/app/featu"]
  N13["Service: Frontend_Fintech/src/app/featu"]
  N14["Component: Frontend_Fintech/src/app/featu"]
  N15["Component: Frontend_Fintech/src/app/featu"]
  N16["Component: Frontend_Fintech/src/app/featu"]
  N17["Component: Frontend_Fintech/src/app/featu"]
  N18["Component: Frontend_Fintech/src/app/featu"]
  N19["Component: Frontend_Fintech/src/app/featu"]
  N20["Service: Frontend_Fintech/src/app/featu"]
  N21["Service: Frontend_Fintech/src/app/featu"]
  N22["Component: Frontend_Fintech/src/app/featu"]
  N23["Component: Frontend_Fintech/src/app/featu"]
  N24["Component: Frontend_Fintech/src/app/featu"]
  N25["Component: Frontend_Fintech/src/app/featu"]
  N26["Component: Frontend_Fintech/src/app/featu"]
  N27["Component: Frontend_Fintech/src/app/featu"]
  N28["Component: Frontend_Fintech/src/app/featu"]
  N29["Component: Frontend_Fintech/src/app/featu"]
  N30["Component: Frontend_Fintech/src/app/featu"]
  N31["Component: Frontend_Fintech/src/app/featu"]
  N32["Component: Frontend_Fintech/src/app/featu"]
  N33["Component: Frontend_Fintech/src/app/featu"]
  N34["Component: Frontend_Fintech/src/app/featu"]
  N35["Component: Frontend_Fintech/src/app/featu"]
  N36["Service: Frontend_Fintech/src/app/featu"]
  N37["Component: Frontend_Fintech/src/app/featu"]
  N38["Component: Frontend_Fintech/src/app/featu"]
  N39["Component: Frontend_Fintech/src/app/featu"]
  N40["Component: Frontend_Fintech/src/app/featu"]
  N41["Component: Frontend_Fintech/src/app/featu"]
  N42["Component: Frontend_Fintech/src/app/featu"]
  N43["Component: Frontend_Fintech/src/app/featu"]
  N44["Component: Frontend_Fintech/src/app/featu"]
  N45["Component: Frontend_Fintech/src/app/featu"]
  N46["Service: Frontend_Fintech/src/app/featu"]
  N47["Component: Frontend_Fintech/src/app/featu"]
  N48["Component: Frontend_Fintech/src/app/featu"]
  N49["Component: Frontend_Fintech/src/app/featu"]
  N50["Component: Frontend_Fintech/src/app/featu"]
  N51["Component: Frontend_Fintech/src/app/featu"]
  N52["Component: Frontend_Fintech/src/app/featu"]
  N53["Component: Frontend_Fintech/src/app/featu"]
  N54["Component: Frontend_Fintech/src/app/featu"]
  N55["Service: Frontend_Fintech/src/app/featu"]
  N56["Component: Frontend_Fintech/src/app/featu"]
  N57["Component: Frontend_Fintech/src/app/featu"]
  N58["Component: Frontend_Fintech/src/app/featu"]
  N59["Component: Frontend_Fintech/src/app/featu"]
  N60["Component: Frontend_Fintech/src/app/featu"]
  N61["Component: Frontend_Fintech/src/app/featu"]
  N62["Component: Frontend_Fintech/src/app/featu"]
  N63["Component: Frontend_Fintech/src/app/featu"]
  N64["Service: Frontend_Fintech/src/app/featu"]
  N65["Service: Frontend_Fintech/src/app/featu"]
  N66["Service: Frontend_Fintech/src/app/featu"]
  N67["Service: Frontend_Fintech/src/app/featu"]
  N68["Component: Frontend_Fintech/src/app/featu"]
  N69["Service: Frontend_Fintech/src/app/featu"]
  N70["Component: Frontend_Fintech/src/app/featu"]
  N71["Service: Frontend_Fintech/src/app/featu"]
  N72["Component: Frontend_Fintech/src/app/featu"]
  N73["Service: Frontend_Fintech/src/app/featu"]
  N74["Component: Frontend_Fintech/src/app/featu"]
  N75["Component: Frontend_Fintech/src/app/featu"]
  N76["Component: Frontend_Fintech/src/app/featu"]
  N77["Component: Frontend_Fintech/src/app/featu"]
  N78["Service: Frontend_Fintech/src/app/featu"]
  N79["Component: Frontend_Fintech/src/app/featu"]
  N80["Component: Frontend_Fintech/src/app/featu"]
  N81["Component: Frontend_Fintech/src/app/featu"]
  N82["Component: Frontend_Fintech/src/app/featu"]
  N83["Service: Frontend_Fintech/src/app/featu"]
  N84["Service: Frontend_Fintech/src/app/featu"]
  N85["Component: Frontend_Fintech/src/app/featu"]
  N86["Component: Frontend_Fintech/src/app/featu"]
  N87["Component: Frontend_Fintech/src/app/featu"]
  N88["Service: Frontend_Fintech/src/app/featu"]
  N89["Component: Frontend_Fintech/src/app/featu"]
  N90["Component: Frontend_Fintech/src/app/featu"]
  N91["Service: Frontend_Fintech/src/app/featu"]
  N92["Service: Frontend_Fintech/src/app/featu"]
  N93["Component: Frontend_Fintech/src/app/featu"]
  N94["Component: Frontend_Fintech/src/app/featu"]
  N95["Component: Frontend_Fintech/src/app/featu"]
  N96["Component: Frontend_Fintech/src/app/featu"]
  N97["Component: Frontend_Fintech/src/app/featu"]
  N98["Component: Frontend_Fintech/src/app/featu"]
  N99["Service: Frontend_Fintech/src/app/featu"]
