apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

patches:
  - path: patches/replicas.yaml
  - path: patches/config.yaml

images:
  - name: fintech/backend
    newTag: staging
  - name: fintech/frontend
    newTag: staging
