apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  labels:
    app.kubernetes.io/name: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
