apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fintech-backend-role
  labels:
    app.kubernetes.io/component: backend
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fintech-worker-role
  labels:
    app.kubernetes.io/component: worker
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fintech-mysql-backup-role
  labels:
    app.kubernetes.io/component: mysql-backup
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
