apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-backend
  labels:
    app.kubernetes.io/component: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-frontend
  labels:
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-worker
  labels:
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fintech-mysql-backup
  labels:
    app.kubernetes.io/component: mysql-backup
automountServiceAccountToken: false
