apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fintech-logs
  labels:
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
