apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

patches:
  - path: patches/config.yaml

images:
  - name: fintech/backend
    newTag: production
  - name: fintech/frontend
    newTag: production
